
package ar.com.syntagma.esphora.conector.servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import fex.dif.afip.gov.ar.ClsFEXGetCMP;
import fex.dif.afip.gov.ar.ClsFEXGetCMPResponse;
import fex.dif.afip.gov.ar.ClsFEXRequest;
import fex.dif.afip.gov.ar.DummyResponse;
import fex.dif.afip.gov.ar.FEXResponseAuthorize;
import fex.dif.afip.gov.ar.FEXResponseCheckPermiso;
import fex.dif.afip.gov.ar.FEXResponseCtz;
import fex.dif.afip.gov.ar.FEXResponseDSTCuit;
import fex.dif.afip.gov.ar.FEXResponseDSTPais;
import fex.dif.afip.gov.ar.FEXResponseIdi;
import fex.dif.afip.gov.ar.FEXResponseInc;
import fex.dif.afip.gov.ar.FEXResponseLastCMP;
import fex.dif.afip.gov.ar.FEXResponseLastID;
import fex.dif.afip.gov.ar.FEXResponseMon;
import fex.dif.afip.gov.ar.FEXResponsePtoVenta;
import fex.dif.afip.gov.ar.FEXResponseTex;
import fex.dif.afip.gov.ar.FEXResponseTipoCbte;
import fex.dif.afip.gov.ar.FEXResponseUmed;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsfex", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/")
@XmlSeeAlso({
    ar.com.syntagma.esphora.conector.servicios.ObjectFactory.class,
    fex.dif.afip.gov.ar.ObjectFactory.class
})
public interface Wsfex {


    /**
     * 
     * @param cuit
     * @param cmp
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseAuthorize
     */
    @WebMethod(operationName = "FEXAuthorize")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXAuthorize", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXAuthorize")
    @ResponseWrapper(localName = "FEXAuthorizeResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXAuthorizeResponse")
    public FEXResponseAuthorize fexAuthorize(
        @WebParam(name = "cmp", targetNamespace = "")
        ClsFEXRequest cmp,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param idPermiso
     * @param cuit
     * @param dstMerc
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseCheckPermiso
     */
    @WebMethod(operationName = "FEXCheck_Permiso")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXCheck_Permiso", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXCheckPermiso")
    @ResponseWrapper(localName = "FEXCheck_PermisoResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXCheckPermisoResponse")
    public FEXResponseCheckPermiso fexCheckPermiso(
        @WebParam(name = "idPermiso", targetNamespace = "")
        String idPermiso,
        @WebParam(name = "dstMerc", targetNamespace = "")
        int dstMerc,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fex.dif.afip.gov.ar.DummyResponse
     */
    @WebMethod(operationName = "FEXDummy")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXDummy", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXDummy")
    @ResponseWrapper(localName = "FEXDummyResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXDummyResponse")
    public DummyResponse fexDummy(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @param cmp
     * @return
     *     returns fex.dif.afip.gov.ar.ClsFEXGetCMPResponse
     */
    @WebMethod(operationName = "FEXGetCMP")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXGetCMP", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetCMP")
    @ResponseWrapper(localName = "FEXGetCMPResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetCMPResponse")
    public ClsFEXGetCMPResponse fexGetCMP(
        @WebParam(name = "cmp", targetNamespace = "")
        ClsFEXGetCMP cmp,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @param tipoComprobante
     * @param puntoVenta
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseLastCMP
     */
    @WebMethod(operationName = "FEXGetLast_CMP")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXGetLast_CMP", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetLastCMP")
    @ResponseWrapper(localName = "FEXGetLast_CMPResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetLastCMPResponse")
    public FEXResponseLastCMP fexGetLastCMP(
        @WebParam(name = "tipoComprobante", targetNamespace = "")
        short tipoComprobante,
        @WebParam(name = "puntoVenta", targetNamespace = "")
        short puntoVenta,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseLastID
     */
    @WebMethod(operationName = "FEXGetLast_ID")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXGetLast_ID", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetLastID")
    @ResponseWrapper(localName = "FEXGetLast_IDResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetLastIDResponse")
    public FEXResponseLastID fexGetLastID(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param idMoneda
     * @param cuit
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseCtz
     */
    @WebMethod(operationName = "FEXGetPARAM_Ctz")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXGetPARAM_Ctz", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMCtz")
    @ResponseWrapper(localName = "FEXGetPARAM_CtzResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMCtzResponse")
    public FEXResponseCtz fexGetPARAMCtz(
        @WebParam(name = "idMoneda", targetNamespace = "")
        String idMoneda,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseDSTCuit
     */
    @WebMethod(operationName = "FEXGetPARAM_DST_CUIT")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXGetPARAM_DST_CUIT", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMDSTCUIT")
    @ResponseWrapper(localName = "FEXGetPARAM_DST_CUITResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMDSTCUITResponse")
    public FEXResponseDSTCuit fexGetPARAMDSTCUIT(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseDSTPais
     */
    @WebMethod(operationName = "FEXGetPARAM_DST_pais")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXGetPARAM_DST_pais", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMDSTPais")
    @ResponseWrapper(localName = "FEXGetPARAM_DST_paisResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMDSTPaisResponse")
    public FEXResponseDSTPais fexGetPARAMDSTPais(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseIdi
     */
    @WebMethod(operationName = "FEXGetPARAM_Idiomas")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXGetPARAM_Idiomas", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMIdiomas")
    @ResponseWrapper(localName = "FEXGetPARAM_IdiomasResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMIdiomasResponse")
    public FEXResponseIdi fexGetPARAMIdiomas(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseInc
     */
    @WebMethod(operationName = "FEXGetPARAM_Incoterms")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXGetPARAM_Incoterms", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMIncoterms")
    @ResponseWrapper(localName = "FEXGetPARAM_IncotermsResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMIncotermsResponse")
    public FEXResponseInc fexGetPARAMIncoterms(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseMon
     */
    @WebMethod(operationName = "FEXGetPARAM_MON")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXGetPARAM_MON", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMMON")
    @ResponseWrapper(localName = "FEXGetPARAM_MONResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMMONResponse")
    public FEXResponseMon fexGetPARAMMON(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponsePtoVenta
     */
    @WebMethod(operationName = "FEXGetPARAM_PtoVenta")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXGetPARAM_PtoVenta", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMPtoVenta")
    @ResponseWrapper(localName = "FEXGetPARAM_PtoVentaResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMPtoVentaResponse")
    public FEXResponsePtoVenta fexGetPARAMPtoVenta(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseTipoCbte
     */
    @WebMethod(operationName = "FEXGetPARAM_Tipo_Cbte")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXGetPARAM_Tipo_Cbte", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMTipoCbte")
    @ResponseWrapper(localName = "FEXGetPARAM_Tipo_CbteResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMTipoCbteResponse")
    public FEXResponseTipoCbte fexGetPARAMTipoCbte(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseTex
     */
    @WebMethod(operationName = "FEXGetPARAM_Tipo_Expo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXGetPARAM_Tipo_Expo", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMTipoExpo")
    @ResponseWrapper(localName = "FEXGetPARAM_Tipo_ExpoResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMTipoExpoResponse")
    public FEXResponseTex fexGetPARAMTipoExpo(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseUmed
     */
    @WebMethod(operationName = "FEXGetPARAM_UMed")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEXGetPARAM_UMed", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMUMed")
    @ResponseWrapper(localName = "FEXGetPARAM_UMedResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEXGetPARAMUMedResponse")
    public FEXResponseUmed fexGetPARAMUMed(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

}
