
package ar.com.syntagma.esphora.conector.servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import fev1.dif.afip.gov.ar.CbteTipoResponse;
import fev1.dif.afip.gov.ar.ConceptoTipoResponse;
import fev1.dif.afip.gov.ar.DocTipoResponse;
import fev1.dif.afip.gov.ar.DummyResponse;
import fev1.dif.afip.gov.ar.FECAEAGetResponse;
import fev1.dif.afip.gov.ar.FECAEARequest;
import fev1.dif.afip.gov.ar.FECAEAResponse;
import fev1.dif.afip.gov.ar.FECAEASinMovConsResponse;
import fev1.dif.afip.gov.ar.FECAEASinMovResponse;
import fev1.dif.afip.gov.ar.FECAERequest;
import fev1.dif.afip.gov.ar.FECAEResponse;
import fev1.dif.afip.gov.ar.FECompConsultaReq;
import fev1.dif.afip.gov.ar.FECompConsultaResponse;
import fev1.dif.afip.gov.ar.FECotizacionResponse;
import fev1.dif.afip.gov.ar.FEPtoVentaResponse;
import fev1.dif.afip.gov.ar.FERecuperaLastCbteResponse;
import fev1.dif.afip.gov.ar.FERegXReqResponse;
import fev1.dif.afip.gov.ar.FETributoResponse;
import fev1.dif.afip.gov.ar.IvaTipoResponse;
import fev1.dif.afip.gov.ar.MonedaResponse;
import fev1.dif.afip.gov.ar.OpcionalTipoResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsfev1", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/")
@XmlSeeAlso({
    ar.com.syntagma.esphora.conector.servicios.ObjectFactory.class,
    fev1.dif.afip.gov.ar.ObjectFactory.class
})
public interface Wsfev1 {


    /**
     * 
     * @param orden
     * @param cuit
     * @param periodo
     * @return
     *     returns fev1.dif.afip.gov.ar.FECAEAGetResponse
     */
    @WebMethod(operationName = "FECAEAConsultar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FECAEAConsultar", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECAEAConsultar")
    @ResponseWrapper(localName = "FECAEAConsultarResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECAEAConsultarResponse")
    public FECAEAGetResponse fecaeaConsultar(
        @WebParam(name = "periodo", targetNamespace = "")
        int periodo,
        @WebParam(name = "orden", targetNamespace = "")
        short orden,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @param feCAEARegInfReq
     * @return
     *     returns fev1.dif.afip.gov.ar.FECAEAResponse
     */
    @WebMethod(operationName = "FECAEARegInformativo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FECAEARegInformativo", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECAEARegInformativo")
    @ResponseWrapper(localName = "FECAEARegInformativoResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECAEARegInformativoResponse")
    public FECAEAResponse fecaeaRegInformativo(
        @WebParam(name = "feCAEARegInfReq", targetNamespace = "")
        FECAEARequest feCAEARegInfReq,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param caea
     * @param cuit
     * @param ptoVta
     * @return
     *     returns fev1.dif.afip.gov.ar.FECAEASinMovConsResponse
     */
    @WebMethod(operationName = "FECAEASinMovimientoConsultar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FECAEASinMovimientoConsultar", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECAEASinMovimientoConsultar")
    @ResponseWrapper(localName = "FECAEASinMovimientoConsultarResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECAEASinMovimientoConsultarResponse")
    public FECAEASinMovConsResponse fecaeaSinMovimientoConsultar(
        @WebParam(name = "caea", targetNamespace = "")
        String caea,
        @WebParam(name = "ptoVta", targetNamespace = "")
        int ptoVta,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param caea
     * @param cuit
     * @param ptoVta
     * @return
     *     returns fev1.dif.afip.gov.ar.FECAEASinMovResponse
     */
    @WebMethod(operationName = "FECAEASinMovimientoInformar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FECAEASinMovimientoInformar", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECAEASinMovimientoInformar")
    @ResponseWrapper(localName = "FECAEASinMovimientoInformarResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECAEASinMovimientoInformarResponse")
    public FECAEASinMovResponse fecaeaSinMovimientoInformar(
        @WebParam(name = "caea", targetNamespace = "")
        String caea,
        @WebParam(name = "ptoVta", targetNamespace = "")
        int ptoVta,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param orden
     * @param cuit
     * @param periodo
     * @return
     *     returns fev1.dif.afip.gov.ar.FECAEAGetResponse
     */
    @WebMethod(operationName = "FECAEASolicitar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FECAEASolicitar", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECAEASolicitar")
    @ResponseWrapper(localName = "FECAEASolicitarResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECAEASolicitarResponse")
    public FECAEAGetResponse fecaeaSolicitar(
        @WebParam(name = "periodo", targetNamespace = "")
        int periodo,
        @WebParam(name = "orden", targetNamespace = "")
        short orden,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @param fer
     * @return
     *     returns fev1.dif.afip.gov.ar.FECAEResponse
     */
    @WebMethod(operationName = "FECAESolicitar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FECAESolicitar", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECAESolicitar")
    @ResponseWrapper(localName = "FECAESolicitarResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECAESolicitarResponse")
    public FECAEResponse fecaeSolicitar(
        @WebParam(name = "fer", targetNamespace = "")
        FECAERequest fer,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @param feCompConsultaReq
     * @return
     *     returns fev1.dif.afip.gov.ar.FECompConsultaResponse
     */
    @WebMethod(operationName = "FECompConsultar")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FECompConsultar", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECompConsultar")
    @ResponseWrapper(localName = "FECompConsultarResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECompConsultarResponse")
    public FECompConsultaResponse feCompConsultar(
        @WebParam(name = "FECompConsultaReq", targetNamespace = "")
        FECompConsultaReq feCompConsultaReq,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param caea
     * @param cuit
     * @param ptoVta
     * @return
     *     returns fev1.dif.afip.gov.ar.FERegXReqResponse
     */
    @WebMethod(operationName = "FECompTotXRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FECompTotXRequest", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECompTotXRequest")
    @ResponseWrapper(localName = "FECompTotXRequestResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECompTotXRequestResponse")
    public FERegXReqResponse feCompTotXRequest(
        @WebParam(name = "caea", targetNamespace = "")
        String caea,
        @WebParam(name = "ptoVta", targetNamespace = "")
        int ptoVta,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @param tipoComprobante
     * @param puntoVenta
     * @return
     *     returns fev1.dif.afip.gov.ar.FERecuperaLastCbteResponse
     */
    @WebMethod(operationName = "FECompUltimoAutorizado")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FECompUltimoAutorizado", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECompUltimoAutorizado")
    @ResponseWrapper(localName = "FECompUltimoAutorizadoResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FECompUltimoAutorizadoResponse")
    public FERecuperaLastCbteResponse feCompUltimoAutorizado(
        @WebParam(name = "tipoComprobante", targetNamespace = "")
        int tipoComprobante,
        @WebParam(name = "puntoVenta", targetNamespace = "")
        int puntoVenta,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @param monId
     * @return
     *     returns fev1.dif.afip.gov.ar.FECotizacionResponse
     */
    @WebMethod(operationName = "FEParamGetCotizacion")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetCotizacion", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetCotizacion")
    @ResponseWrapper(localName = "FEParamGetCotizacionResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetCotizacionResponse")
    public FECotizacionResponse feParamGetCotizacion(
        @WebParam(name = "monId", targetNamespace = "")
        String monId,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fev1.dif.afip.gov.ar.FEPtoVentaResponse
     */
    @WebMethod(operationName = "FEParamGetPtosVenta")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetPtosVenta", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetPtosVenta")
    @ResponseWrapper(localName = "FEParamGetPtosVentaResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetPtosVentaResponse")
    public FEPtoVentaResponse feParamGetPtosVenta(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fev1.dif.afip.gov.ar.CbteTipoResponse
     */
    @WebMethod(operationName = "FEParamGetTiposCbte")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetTiposCbte", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetTiposCbte")
    @ResponseWrapper(localName = "FEParamGetTiposCbteResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetTiposCbteResponse")
    public CbteTipoResponse feParamGetTiposCbte(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fev1.dif.afip.gov.ar.ConceptoTipoResponse
     */
    @WebMethod(operationName = "FEParamGetTiposConcepto")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetTiposConcepto", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetTiposConcepto")
    @ResponseWrapper(localName = "FEParamGetTiposConceptoResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetTiposConceptoResponse")
    public ConceptoTipoResponse feParamGetTiposConcepto(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fev1.dif.afip.gov.ar.DocTipoResponse
     */
    @WebMethod(operationName = "FEParamGetTiposDoc")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetTiposDoc", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetTiposDoc")
    @ResponseWrapper(localName = "FEParamGetTiposDocResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetTiposDocResponse")
    public DocTipoResponse feParamGetTiposDoc(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fev1.dif.afip.gov.ar.IvaTipoResponse
     */
    @WebMethod(operationName = "FEParamGetTiposIva")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetTiposIva", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetTiposIva")
    @ResponseWrapper(localName = "FEParamGetTiposIvaResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetTiposIvaResponse")
    public IvaTipoResponse feParamGetTiposIva(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fev1.dif.afip.gov.ar.MonedaResponse
     */
    @WebMethod(operationName = "FEParamGetTiposMonedas")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetTiposMonedas", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetTiposMonedas")
    @ResponseWrapper(localName = "FEParamGetTiposMonedasResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetTiposMonedasResponse")
    public MonedaResponse feParamGetTiposMonedas(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fev1.dif.afip.gov.ar.OpcionalTipoResponse
     */
    @WebMethod(operationName = "FEParamGetTiposOpcional")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetTiposOpcional", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetTiposOpcional")
    @ResponseWrapper(localName = "FEParamGetTiposOpcionalResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetTiposOpcionalResponse")
    public OpcionalTipoResponse feParamGetTiposOpcional(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fev1.dif.afip.gov.ar.FETributoResponse
     */
    @WebMethod(operationName = "FEParamGetTiposTributo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEParamGetTiposTributo", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetTiposTributo")
    @ResponseWrapper(localName = "FEParamGetTiposTributoResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEParamGetTiposTributoResponse")
    public FETributoResponse feParamGetTiposTributo(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns fev1.dif.afip.gov.ar.DummyResponse
     */
    @WebMethod(operationName = "FEV1Dummy")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEV1Dummy", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEV1Dummy")
    @ResponseWrapper(localName = "FEV1DummyResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEV1DummyResponse")
    public DummyResponse fev1Dummy(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

}
