
package https.wsaahomo_afip_gov_ar.ws.services.logincms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LoginCMS", targetNamespace = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms")
@XmlSeeAlso({
    https.wsaahomo_afip_gov_ar.ws.services.logincms.ObjectFactory.class,
    gov.afip.desein.dvadac.sua.view.wsaa.ObjectFactory.class
})
public interface LoginCMS {


    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     * @throws LoginFault_Exception
     */
    @WebMethod
    @WebResult(name = "loginCmsReturn", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov")
    @RequestWrapper(localName = "loginCms", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov", className = "gov.afip.desein.dvadac.sua.view.wsaa.LoginCms")
    @ResponseWrapper(localName = "loginCmsResponse", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov", className = "gov.afip.desein.dvadac.sua.view.wsaa.LoginCmsResponse")
    public String loginCms(
        @WebParam(name = "in0", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov")
        String in0)
        throws LoginFault_Exception
    ;

}
