
package fex.dif.afip.gov.ar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://ar.gov.afip.dif.fex/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * Autoriza un comprobante, devolviendo  su CAE correspondiente
     * 
     * @param cmp
     * @param auth
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseAuthorize
     */
    @WebMethod(operationName = "FEXAuthorize", action = "http://ar.gov.afip.dif.fex/FEXAuthorize")
    @WebResult(name = "FEXAuthorizeResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXAuthorize", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXAuthorize")
    @ResponseWrapper(localName = "FEXAuthorizeResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXAuthorizeResponse")
    public FEXResponseAuthorize fexAuthorize(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXAuthRequest auth,
        @WebParam(name = "Cmp", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXRequest cmp);

    /**
     * Recupera los datos completos de un comprobante ya autorizado
     * 
     * @param cmp
     * @param auth
     * @return
     *     returns fex.dif.afip.gov.ar.ClsFEXGetCMPResponse
     */
    @WebMethod(operationName = "FEXGetCMP", action = "http://ar.gov.afip.dif.fex/FEXGetCMP")
    @WebResult(name = "FEXGetCMPResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXGetCMP", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetCMP")
    @ResponseWrapper(localName = "FEXGetCMPResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetCMPResponse")
    public ClsFEXGetCMPResponse fexGetCMP(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXAuthRequest auth,
        @WebParam(name = "Cmp", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXGetCMP cmp);

    /**
     * Recupera el listado de los tipos de comprobante  y su codigo utilizables en servicio de autorizacion
     * 
     * @param auth
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseTipoCbte
     */
    @WebMethod(operationName = "FEXGetPARAM_Tipo_Cbte", action = "http://ar.gov.afip.dif.fex/FEXGetPARAM_Tipo_Cbte")
    @WebResult(name = "FEXGetPARAM_Tipo_CbteResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXGetPARAM_Tipo_Cbte", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMTipoCbte")
    @ResponseWrapper(localName = "FEXGetPARAM_Tipo_CbteResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMTipoCbteResponse")
    public FEXResponseTipoCbte fexGetPARAMTipoCbte(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXAuthRequest auth);

    /**
     * Recupera el listado de los tipos de exportacion  y sus codigo utilizables en servicio de autorizacion
     * 
     * @param auth
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseTex
     */
    @WebMethod(operationName = "FEXGetPARAM_Tipo_Expo", action = "http://ar.gov.afip.dif.fex/FEXGetPARAM_Tipo_Expo")
    @WebResult(name = "FEXGetPARAM_Tipo_ExpoResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXGetPARAM_Tipo_Expo", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMTipoExpo")
    @ResponseWrapper(localName = "FEXGetPARAM_Tipo_ExpoResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMTipoExpoResponse")
    public FEXResponseTex fexGetPARAMTipoExpo(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXAuthRequest auth);

    /**
     * Recupera el listado Incoterms  utilizables en servicio de autorizacion
     * 
     * @param auth
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseInc
     */
    @WebMethod(operationName = "FEXGetPARAM_Incoterms", action = "http://ar.gov.afip.dif.fex/FEXGetPARAM_Incoterms")
    @WebResult(name = "FEXGetPARAM_IncotermsResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXGetPARAM_Incoterms", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMIncoterms")
    @ResponseWrapper(localName = "FEXGetPARAM_IncotermsResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMIncotermsResponse")
    public FEXResponseInc fexGetPARAMIncoterms(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXAuthRequest auth);

    /**
     * Recupera el listado de los idiomas  y sus codigos utilizables en servicio de autorizacion
     * 
     * @param auth
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseIdi
     */
    @WebMethod(operationName = "FEXGetPARAM_Idiomas", action = "http://ar.gov.afip.dif.fex/FEXGetPARAM_Idiomas")
    @WebResult(name = "FEXGetPARAM_IdiomasResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXGetPARAM_Idiomas", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMIdiomas")
    @ResponseWrapper(localName = "FEXGetPARAM_IdiomasResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMIdiomasResponse")
    public FEXResponseIdi fexGetPARAMIdiomas(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXAuthRequest auth);

    /**
     * Recupera el listado de las unidades de medida  y su codigo utilizables en servicio de autorizacion
     * 
     * @param auth
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseUmed
     */
    @WebMethod(operationName = "FEXGetPARAM_UMed", action = "http://ar.gov.afip.dif.fex/FEXGetPARAM_UMed")
    @WebResult(name = "FEXGetPARAM_UMedResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXGetPARAM_UMed", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMUMed")
    @ResponseWrapper(localName = "FEXGetPARAM_UMedResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMUMedResponse")
    public FEXResponseUmed fexGetPARAMUMed(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXAuthRequest auth);

    /**
     * Recupera el listado de paises
     * 
     * @param auth
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseDSTPais
     */
    @WebMethod(operationName = "FEXGetPARAM_DST_pais", action = "http://ar.gov.afip.dif.fex/FEXGetPARAM_DST_pais")
    @WebResult(name = "FEXGetPARAM_DST_paisResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXGetPARAM_DST_pais", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMDSTPais")
    @ResponseWrapper(localName = "FEXGetPARAM_DST_paisResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMDSTPaisResponse")
    public FEXResponseDSTPais fexGetPARAMDSTPais(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXAuthRequest auth);

    /**
     * Recupera el listado de las cuits de los paises de destinacion
     * 
     * @param auth
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseDSTCuit
     */
    @WebMethod(operationName = "FEXGetPARAM_DST_CUIT", action = "http://ar.gov.afip.dif.fex/FEXGetPARAM_DST_CUIT")
    @WebResult(name = "FEXGetPARAM_DST_CUITResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXGetPARAM_DST_CUIT", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMDSTCUIT")
    @ResponseWrapper(localName = "FEXGetPARAM_DST_CUITResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMDSTCUITResponse")
    public FEXResponseDSTCuit fexGetPARAMDSTCUIT(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXAuthRequest auth);

    /**
     * Recupera el listado  de monedas y su codigo utilizables en servicio de autorizacion
     * 
     * @param auth
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseMon
     */
    @WebMethod(operationName = "FEXGetPARAM_MON", action = "http://ar.gov.afip.dif.fex/FEXGetPARAM_MON")
    @WebResult(name = "FEXGetPARAM_MONResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXGetPARAM_MON", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMMON")
    @ResponseWrapper(localName = "FEXGetPARAM_MONResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMMONResponse")
    public FEXResponseMon fexGetPARAMMON(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXAuthRequest auth);

    /**
     * Recupera el ultimos comprobante autorizado
     * 
     * @param auth
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseLastCMP
     */
    @WebMethod(operationName = "FEXGetLast_CMP", action = "http://ar.gov.afip.dif.fex/FEXGetLast_CMP")
    @WebResult(name = "FEXGetLast_CMPResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXGetLast_CMP", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetLastCMP")
    @ResponseWrapper(localName = "FEXGetLast_CMPResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetLastCMPResponse")
    public FEXResponseLastCMP fexGetLastCMP(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXLastCMP auth);

    /**
     * Metodo dummy para verificacion de funcionamiento
     * 
     * @return
     *     returns fex.dif.afip.gov.ar.DummyResponse
     */
    @WebMethod(operationName = "FEXDummy", action = "http://ar.gov.afip.dif.fex/FEXDummy")
    @WebResult(name = "FEXDummyResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXDummy", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXDummy")
    @ResponseWrapper(localName = "FEXDummyResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXDummyResponse")
    public DummyResponse fexDummy();

    /**
     * Recupera la cotizacion de la moneda consultada y su  fecha 
     * 
     * @param auth
     * @param monId
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseCtz
     */
    @WebMethod(operationName = "FEXGetPARAM_Ctz", action = "http://ar.gov.afip.dif.fex/FEXGetPARAM_Ctz")
    @WebResult(name = "FEXGetPARAM_CtzResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXGetPARAM_Ctz", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMCtz")
    @ResponseWrapper(localName = "FEXGetPARAM_CtzResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMCtzResponse")
    public FEXResponseCtz fexGetPARAMCtz(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXAuthRequest auth,
        @WebParam(name = "Mon_id", targetNamespace = "http://ar.gov.afip.dif.fex/")
        String monId);

    /**
     * Recupera el ultimo ID y su  fecha 
     * 
     * @param auth
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseLastID
     */
    @WebMethod(operationName = "FEXGetLast_ID", action = "http://ar.gov.afip.dif.fex/FEXGetLast_ID")
    @WebResult(name = "FEXGetLast_IDResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXGetLast_ID", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetLastID")
    @ResponseWrapper(localName = "FEXGetLast_IDResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetLastIDResponse")
    public FEXResponseLastID fexGetLastID(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXAuthRequest auth);

    /**
     * Recupera el listado de los puntos de venta registrados para Factura electronica de exportacion - WS y su estado
     * 
     * @param auth
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponsePtoVenta
     */
    @WebMethod(operationName = "FEXGetPARAM_PtoVenta", action = "http://ar.gov.afip.dif.fex/FEXGetPARAM_PtoVenta")
    @WebResult(name = "FEXGetPARAM_PtoVentaResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXGetPARAM_PtoVenta", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMPtoVenta")
    @ResponseWrapper(localName = "FEXGetPARAM_PtoVentaResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXGetPARAMPtoVentaResponse")
    public FEXResponsePtoVenta fexGetPARAMPtoVenta(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXAuthRequest auth);

    /**
     * Verifica la  existencia de la permiso/pais de destinacion  de embarque ingresado
     * 
     * @param idPermiso
     * @param dstMerc
     * @param auth
     * @return
     *     returns fex.dif.afip.gov.ar.FEXResponseCheckPermiso
     */
    @WebMethod(operationName = "FEXCheck_Permiso", action = "http://ar.gov.afip.dif.fex/FEXCheck_Permiso")
    @WebResult(name = "FEXCheck_PermisoResult", targetNamespace = "http://ar.gov.afip.dif.fex/")
    @RequestWrapper(localName = "FEXCheck_Permiso", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXCheckPermiso")
    @ResponseWrapper(localName = "FEXCheck_PermisoResponse", targetNamespace = "http://ar.gov.afip.dif.fex/", className = "fex.dif.afip.gov.ar.FEXCheckPermisoResponse")
    public FEXResponseCheckPermiso fexCheckPermiso(
        @WebParam(name = "Auth", targetNamespace = "http://ar.gov.afip.dif.fex/")
        ClsFEXAuthRequest auth,
        @WebParam(name = "ID_Permiso", targetNamespace = "http://ar.gov.afip.dif.fex/")
        String idPermiso,
        @WebParam(name = "Dst_merc", targetNamespace = "http://ar.gov.afip.dif.fex/")
        int dstMerc);

}
