
package facturaelectronica.dif.afip.gov.ar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * Retorna la cantidad maxima de registros de detalle que puede tener una invocacion al FEAutorizarRequest.
     * 
     * @param argAuth
     * @return
     *     returns facturaelectronica.dif.afip.gov.ar.FERecuperaQTYResponse
     */
    @WebMethod(operationName = "FERecuperaQTYRequest", action = "http://ar.gov.afip.dif.facturaelectronica/FERecuperaQTYRequest")
    @WebResult(name = "FERecuperaQTYRequestResult", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
    @RequestWrapper(localName = "FERecuperaQTYRequest", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/", className = "facturaelectronica.dif.afip.gov.ar.FERecuperaQTYRequest")
    @ResponseWrapper(localName = "FERecuperaQTYRequestResponse", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/", className = "facturaelectronica.dif.afip.gov.ar.FERecuperaQTYRequestResponse")
    public FERecuperaQTYResponse feRecuperaQTYRequest(
        @WebParam(name = "argAuth", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
        FEAuthRequest argAuth);

    /**
     * Metodo dummy para verificacion basica de funcionamiento.
     * 
     * @return
     *     returns facturaelectronica.dif.afip.gov.ar.DummyResponse
     */
    @WebMethod(operationName = "FEDummy", action = "http://ar.gov.afip.dif.facturaelectronica/FEDummy")
    @WebResult(name = "FEDummyResult", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
    @RequestWrapper(localName = "FEDummy", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/", className = "facturaelectronica.dif.afip.gov.ar.FEDummy")
    @ResponseWrapper(localName = "FEDummyResponse", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/", className = "facturaelectronica.dif.afip.gov.ar.FEDummyResponse")
    public DummyResponse feDummy();

    /**
     * Retorna el ultimo comprobante autorizado para el  tipo de comprobante /cuit / punto de venta ingresado.
     * 
     * @param argTCMP
     * @param argAuth
     * @return
     *     returns facturaelectronica.dif.afip.gov.ar.FERecuperaLastCMPResponse
     */
    @WebMethod(operationName = "FERecuperaLastCMPRequest", action = "http://ar.gov.afip.dif.facturaelectronica/FERecuperaLastCMPRequest")
    @WebResult(name = "FERecuperaLastCMPRequestResult", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
    @RequestWrapper(localName = "FERecuperaLastCMPRequest", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/", className = "facturaelectronica.dif.afip.gov.ar.FERecuperaLastCMPRequest")
    @ResponseWrapper(localName = "FERecuperaLastCMPRequestResponse", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/", className = "facturaelectronica.dif.afip.gov.ar.FERecuperaLastCMPRequestResponse")
    public FERecuperaLastCMPResponse feRecuperaLastCMPRequest(
        @WebParam(name = "argAuth", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
        FEAuthRequest argAuth,
        @WebParam(name = "argTCMP", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
        FELastCMPtype argTCMP);

    /**
     * Retorna el ultimo numero de Request.
     * 
     * @param argAuth
     * @return
     *     returns facturaelectronica.dif.afip.gov.ar.FEUltNroResponse
     */
    @WebMethod(operationName = "FEUltNroRequest", action = "http://ar.gov.afip.dif.facturaelectronica/FEUltNroRequest")
    @WebResult(name = "FEUltNroRequestResult", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
    @RequestWrapper(localName = "FEUltNroRequest", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/", className = "facturaelectronica.dif.afip.gov.ar.FEUltNroRequest")
    @ResponseWrapper(localName = "FEUltNroRequestResponse", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/", className = "facturaelectronica.dif.afip.gov.ar.FEUltNroRequestResponse")
    public FEUltNroResponse feUltNroRequest(
        @WebParam(name = "argAuth", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
        FEAuthRequest argAuth);

    /**
     * Dado un lote de comprobantes retorna el mismo autorizado con el CAE otorgado.
     * 
     * @param fer
     * @param argAuth
     * @return
     *     returns facturaelectronica.dif.afip.gov.ar.FEResponse
     */
    @WebMethod(operationName = "FEAutRequest", action = "http://ar.gov.afip.dif.facturaelectronica/FEAutRequest")
    @WebResult(name = "FEAutRequestResult", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
    @RequestWrapper(localName = "FEAutRequest", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/", className = "facturaelectronica.dif.afip.gov.ar.FEAutRequest")
    @ResponseWrapper(localName = "FEAutRequestResponse", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/", className = "facturaelectronica.dif.afip.gov.ar.FEAutRequestResponse")
    public FEResponse feAutRequest(
        @WebParam(name = "argAuth", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
        FEAuthRequest argAuth,
        @WebParam(name = "Fer", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
        FERequest fer);

    /**
     * Consulta el CAE.
     * 
     * @param argCAERequest
     * @param argAuth
     * @return
     *     returns facturaelectronica.dif.afip.gov.ar.FEConsultaCAEResponse
     */
    @WebMethod(operationName = "FEConsultaCAERequest", action = "http://ar.gov.afip.dif.facturaelectronica/FEConsultaCAERequest")
    @WebResult(name = "FEConsultaCAERequestResult", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
    @RequestWrapper(localName = "FEConsultaCAERequest", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/", className = "facturaelectronica.dif.afip.gov.ar.FEConsultaCAERequest")
    @ResponseWrapper(localName = "FEConsultaCAERequestResponse", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/", className = "facturaelectronica.dif.afip.gov.ar.FEConsultaCAERequestResponse")
    public FEConsultaCAEResponse feConsultaCAERequest(
        @WebParam(name = "argAuth", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
        FEAuthRequest argAuth,
        @WebParam(name = "argCAERequest", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/")
        FEConsultaCAEReq argCAERequest);

}
