
package facturaelectronica.dif.afip.gov.ar;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * AFIP Web Service de Facturacion Electronica - Version 1
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Service", targetNamespace = "http://ar.gov.afip.dif.facturaelectronica/", wsdlLocation = "file:/Users/laura.spairani/Downloads/wsfeWsdl.xml")
public class Service
    extends javax.xml.ws.Service
{

    private final static URL SERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(facturaelectronica.dif.afip.gov.ar.Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = facturaelectronica.dif.afip.gov.ar.Service.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/laura.spairani/Downloads/wsfeWsdl.xml");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/laura.spairani/Downloads/wsfeWsdl.xml', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICE_WSDL_LOCATION = url;
    }

    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service() {
        super(SERVICE_WSDL_LOCATION, new QName("http://ar.gov.afip.dif.facturaelectronica/", "Service"));
    }

    /**
     * 
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap")
    public ServiceSoap getServiceSoap() {
        return super.getPort(new QName("http://ar.gov.afip.dif.facturaelectronica/", "ServiceSoap"), ServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceSoap
     */
    @WebEndpoint(name = "ServiceSoap")
    public ServiceSoap getServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ar.gov.afip.dif.facturaelectronica/", "ServiceSoap"), ServiceSoap.class, features);
    }

}
