
package ar.com.syntagma.esphora.conector.servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import facturaelectronica.dif.afip.gov.ar.DummyResponse;
import facturaelectronica.dif.afip.gov.ar.FEConsultaCAEReq;
import facturaelectronica.dif.afip.gov.ar.FEConsultaCAEResponse;
import facturaelectronica.dif.afip.gov.ar.FERecuperaLastCMPResponse;
import facturaelectronica.dif.afip.gov.ar.FERecuperaQTYResponse;
import facturaelectronica.dif.afip.gov.ar.FERequest;
import facturaelectronica.dif.afip.gov.ar.FEResponse;
import facturaelectronica.dif.afip.gov.ar.FEUltNroResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "wsfe", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/")
@XmlSeeAlso({
    facturaelectronica.dif.afip.gov.ar.ObjectFactory.class,
    ar.com.syntagma.esphora.conector.servicios.ObjectFactory.class
})
public interface Wsfe {


    /**
     * 
     * @param cuit
     * @param fer
     * @return
     *     returns facturaelectronica.dif.afip.gov.ar.FEResponse
     */
    @WebMethod(operationName = "FEAutRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEAutRequest", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEAutRequest")
    @ResponseWrapper(localName = "FEAutRequestResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEAutRequestResponse")
    public FEResponse feAutRequest(
        @WebParam(name = "fer", targetNamespace = "")
        FERequest fer,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @param feConsultaCAEReq
     * @return
     *     returns facturaelectronica.dif.afip.gov.ar.FEConsultaCAEResponse
     */
    @WebMethod(operationName = "FEConsultaCAERequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEConsultaCAERequest", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEConsultaCAERequest")
    @ResponseWrapper(localName = "FEConsultaCAERequestResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEConsultaCAERequestResponse")
    public FEConsultaCAEResponse feConsultaCAERequest(
        @WebParam(name = "FEConsultaCAEReq", targetNamespace = "")
        FEConsultaCAEReq feConsultaCAEReq,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns facturaelectronica.dif.afip.gov.ar.DummyResponse
     */
    @WebMethod(operationName = "FEDummy")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEDummy", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEDummy")
    @ResponseWrapper(localName = "FEDummyResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEDummyResponse")
    public DummyResponse feDummy(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @param tipoComprobante
     * @param puntoVenta
     * @return
     *     returns facturaelectronica.dif.afip.gov.ar.FERecuperaLastCMPResponse
     */
    @WebMethod(operationName = "FERecuperaLastCMPRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FERecuperaLastCMPRequest", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FERecuperaLastCMPRequest")
    @ResponseWrapper(localName = "FERecuperaLastCMPRequestResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FERecuperaLastCMPRequestResponse")
    public FERecuperaLastCMPResponse feRecuperaLastCMPRequest(
        @WebParam(name = "tipoComprobante", targetNamespace = "")
        int tipoComprobante,
        @WebParam(name = "puntoVenta", targetNamespace = "")
        int puntoVenta,
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns facturaelectronica.dif.afip.gov.ar.FERecuperaQTYResponse
     */
    @WebMethod(operationName = "FERecuperaQTYRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FERecuperaQTYRequest", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FERecuperaQTYRequest")
    @ResponseWrapper(localName = "FERecuperaQTYRequestResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FERecuperaQTYRequestResponse")
    public FERecuperaQTYResponse feRecuperaQTYRequest(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

    /**
     * 
     * @param cuit
     * @return
     *     returns facturaelectronica.dif.afip.gov.ar.FEUltNroResponse
     */
    @WebMethod(operationName = "FEUltNroRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FEUltNroRequest", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEUltNroRequest")
    @ResponseWrapper(localName = "FEUltNroRequestResponse", targetNamespace = "http://servicios.conector.esphora.syntagma.com.ar/", className = "ar.com.syntagma.esphora.conector.servicios.FEUltNroRequestResponse")
    public FEUltNroResponse feUltNroRequest(
        @WebParam(name = "cuit", targetNamespace = "")
        long cuit);

}
